### PR TITLE
Multiple improvements

### PR DESCRIPTION
**Pull request by lelvisl**
Hi!
I want to say thank for your wonderful project and bring some useful improvements.
- move project to go modules
- remove vendor
- use go embed instead of go-binary and remove all about old assets (go 1.16 feature)
- pin cockroach version in tests
- remove golang.org/x/tools/cmd/cover (not maintained and moved to standart library)
- pin gox version (go 1.16 feature)
- update ci to go 1.16

If some changes (as removing vendor) don't fit project, just say it.

### CODE REVIEW

**Comment by lelvisl** [comment]
@sosedoff, i have 2 questions:
- can you update go to 1.16 in https://github.com/sosedoff/actions/blob/master/golang-build/Dockerfile
- should i squash commits in this PR?

**Comment by sosedoff** [comment]
i see you're dropping support of earlier versions of go, whats the main reason for such a change?

**Comment by lelvisl** [comment]
(i think) it's acceptable to this project, because this is a binary, not a library. 
main reason- go embed - you don't need to use out of box tools and have a lot of generated code: https://golang.org/pkg/embed/

it's also useful for use go install with pinned version of tooling (gox) - you can see at makefile.

**Comment by sosedoff** [comment]
Yes, this is primarily a binary tool, tho i want to have an option to support older go versions when it comes to building it from source (backwards compatibility).  Right now the project is still go-get'able, hence the assets included in the code.

- Go Modules: I dont have any objection to switching to go modules, just didn't really have any time to get that done. 
- Go Embed: It looks promising, however I haven't switched to the latest 1.16 yet and will have to heck out the embed stuff first.

You might be packing way too many changes into a single PR, i would prefer to deal with scoped PRs, like `dep` -> `go mod` change as a separate isolated PR, the static assets change separately, etc etc.

**Comment by lelvisl** [comment]
I will made separate PRs. But they will depent on each other.
First will be go modules with remove vendor (with fixes) and will include
- pin cockroach version in tests
- remove golang.org/x/tools/cmd/cover (not maintained and moved to standart library)

Second will be with go 1.16 features
- use go embed instead of go-binary and remove all about old assets (go 1.16 feature)
- pin gox version (go 1.16 feature)
- update ci to go 1.16

Ok?

**Pull request closed without merging**
