### PR TITLE
Use quoted identifier for TableInfo query

### PR DESCRIPTION
**Pull request by od0**
Great work with this project!

I came across an issue with table names that include the `.` character. While not typically recommended, it is supported in Postgres with quoted identifiers for table names.

To see the issue, create a table name with a `.` such as `foo.bar`. If you click on the table, you will see `ERROR: pq: relation "public.foo" does not exist`. I dug into it a bit, and it looks like of the three API queries that are sent when clicking on a table, one of them (`/info`) returns a 400. 

Pgweb otherwise supports it (e.g. `TableRows` and `TableRowCount` separate the schema and table and use a quoted identifier like so: `sql := fmt.Sprintf(`SELECT * FROM "%s"."%s"`, schema, table)`). `TableInfo`, however, uses a raw query from `statement/sql.go`. In that query, there a few calls to PG functions which attempt to interpret the passed string in schema.table format and fail. I updated these calls to separate the schema and table and use the PG function `quote_ident` to wrap the table name to handle characters such as `.`

Please view this very much as a pull request and not a merge request - I'd love to make sure this meets your standards so just let me know if there's anything else I need to do here!

### CODE REVIEW

**Comment by cbandy** [comment]
What if the schema has a `.` in it?

**Comment by od0** [comment]
@cbandy good question - I wanted to include that but I think it would require a bit more of a refactor to store the schema and table separately (instead of a single string that gets parsed by `getSchemaAndTable`). That would also mean updating the API routes.

**Comment by sosedoff** [comment]
@od0 if you wish to move forward with changes (current or new ones) please include some tests. There's a sample database sql file, you can add new instructions to the end.

**Comment by od0** [comment]
@sosedoff sounds good will get that added

**Comment by sosedoff** [comment]
@od0 hey, any update? are you still going to work on this issue?

**Comment by od0** [comment]
@sosedoff sure - apologies for the delay. I started to write a test for this but I'm not 100% sure what's helpful here. Should I modify the existing database creation script to include tables with `.` in the name, and a test in `client_test.go` to verify that they're parsed properly?

**Comment by sosedoff** [comment]
yeah, you dont have to touch any existing tables, just add a new one and the test case to verify it works.

**Comment by sosedoff** [comment]
@od0 Feel free to resubmit when you're ready.

**Pull request closed without merging**
