### PR TITLE
CSV Import (Issue #281)

### PR DESCRIPTION
**Pull request by budden**

### CODE REVIEW

**Comment by budden** [comment]
I think I made it work finally. Maybe test suite is a bit over-engineered, which was not expected initially. Can you please review ASAP. Actually a motive beyond this work is to collect a portfolio for subsequent hiring in  a Golang-related area. So far I only have contributed to gitql, but that's too trivial and not very typical golang application. I started this project as a "low hanging fruit", but this become a sort of moving target hunt and I grandly underestimated the effort required for the test infratstructure :)

**Comment by sosedoff** [comment]
1. ParseFieldDelimiter belongs to api/helpers.go
2. Replace regular expression with case-insensitive and shorter version: `(i?)^[\w][\w$]*$`
3. Do not panic in isPostgresqlIdentifierRequiringNoQuoting, just return an error (and handle it)

**Comment by budden** [comment]
> 1. ParseFieldDelimiter belongs to api/helpers.go
Will do
> 2. Replace regular expression with case-insensitive and shorter version: `(i?)^[\w][\w$]*$`
It is a wrong one, because 
`SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_). Subsequent characters in an identifier or key word can be letters, underscores, digits (0-9), or dollar signs ($). `. Your suggestion will match `12`. I'll take `^[a-zA-Z_][\w$]*$`
> 3. Do not panic in isPostgresqlIdentifierRequiringNoQuoting, just return an error (and handle it)
Will do, however I have no idea how regex matching can err. This is why I put panic there.

**Comment by budden** [comment]
Hi! Any news?

**Comment by sosedoff** [comment]
Sorry, i've been busy with other stuff. I'll definitely test drive the updated features this weekend and hopefully merge.

**Comment by budden** [comment]
Hi! Sorry for annoyance, but what about this one? :)

**Pull request closed without merging**
