### PR TITLE
go 1.16 features

### PR DESCRIPTION
**Pull request by lelvisl**
- use go embed instead of go-binary and remove all about old assets (go 1.16 feature)
- pin gox version (go 1.16 feature)
- update ci to go 1.16

### CODE REVIEW

**Comment by lelvisl** [comment]
#508

**Comment by lelvisl** [comment]
About go get - it still works, you can check on my couchbase_exporter:

```
go install github.com/lelvisl/couchbase_exporter@v1.0.1
```

version is text file and embedded.
Оr you can import package version from couchbase_exporter to your test app, compile and check.

**Comment by lelvisl** [comment]
@sosedoff what do you think about this PR?

**Comment by sosedoff** [comment]
Sorry havent gotten a chance to look over changes

**Comment by lelvisl** [comment]
may be?)

**Comment by sosedoff** [comment]
yep, i did give it a try last night so will be merging soon

**Pull request merged**
