### PR TITLE
Isolate custom query contents between sessions #280

### PR DESCRIPTION
**Pull request by szemek**
I replaced localStorage with sessionStorage.

### CODE REVIEW

**Comment by sosedoff** [comment]
This change should also account for different modes. If in single session mode - the query data should be available in every tab (just like it works right now), but when it runs in multi-session mode it should only use session storage.

**Comment by szemek** [comment]
@sosedoff maybe I missed something, but is there any option to check which mode is used on JavaScript side? If not I was thinking about passing this piece of information via HTTP header or in payload (/connection or /connect endpoint).

**Comment by sosedoff** [comment]
I thought i had it before, but seems like that piece of work has never made it back to master. 
Multi-session flag is not currently present in `/connection` endpoint, so you can add it as well. See example: https://github.com/sosedoff/pgweb/blob/master/pkg/api/api.go#L391

**Comment by szemek** [comment]
Hmm, I thought about endpoints and I'm not sure whether, in current state of codebase, extending `GET /connection` will be enough.

Pretty much there are 2 scenarios when connecting to database

* `GET /connection (400 error) -> POST /connect`, we are not connected, we fill form and connect
* `GET /connection`, we are already connected

Adding info about single / multiple session(s) to responses for both endpoints `GET /connection` and `POST /connect` seems like a bad idea to me.

**Pull request closed without merging**
