### PR TITLE
Remove double click action on cell

### PR DESCRIPTION
**Pull request by sosedoff**
Removes the confusing behavior when double clicking on the cell. Textarea was for copying data and not for editing like most people assumed.

### CODE REVIEW

**Comment by Tom-Fawcett** [comment]
@sosedoff following this change how do you recommend viewing the full contents of a long text field?

Thanks for your work :slightly_smiling_face:

**Comment by sosedoff** [comment]
@Tom-Fawcett you can right-click on the cell and copy the value using context menu.

**Comment by Tom-Fawcett** [comment]
@sosedoff so for a long value I'd need to copy and paste it somewhere else to view it fully?

Thanks

**Comment by sosedoff** [comment]
Something like that yea. Im all ears if you have suggestions for this feature, i just dont use it often so havent really implemented a replacement. The old flow confused a lot of people so i removed it.

**Comment by Tom-Fawcett** [comment]
An integrated way to view fully would be useful :slightly_smiling_face: 

E.g
* Cell context menu -> View -> _a pop up viewer_
* Or bring back double click but with the contents being read only (not giving the false impression that it's editable)

**Comment by sosedoff** [comment]
A popup makes more sense to me here

**Comment by Tom-Fawcett** [comment]
I've raised #633 as a suggestion :slightly_smiling_face:

**Pull request merged**
