### PR TITLE
Fixed broken export to CSV/JSON/XML, added automatic SQL query generation.

### PR DESCRIPTION
**Pull request by cchesk**
- Fixed broken export to CSV/JSON/XML if there's a hashmark in the URL. Previously, the export failed after the first time.
- The SQL query now gets updated if the user selects, filters, or sorts a table. This both allows the export of filtered results and allows users to see the SQL behind the results.

What's your opinion on allowing multiple filters?

### CODE REVIEW

**Comment by sosedoff** [comment]
RE issue with export - thanks for catching that. Would love a separate clean PR. 

RE other things: i don't see the point of updating the custom query when you browse table rows with any applied filters. If i'm in the process of writing the custom query it will override it as soon as i hit "rows". At least that's what i see in the source code. The purpose of custom sql query editor was to able to use both features at the same time. Perhaps the best way to address what you're asking for is to record all queries that happen on `/rows/` endpoint to the history.

**Comment by cchesk** [comment]
I've filed a seperate clean PR for the export issue.

I see why you're not a fan of the custom SQL query override. For my use case, it would be great if users without knowledge of SQL would be able to export filtered and sorted results. To avoid the conflict with overriding custom SQL queries, it might make sense to add export buttons to the rows tab instead.
Additionally, by displaying a SQL version of the current request, users can learn the basics of SQL without having to write any. Maybe it might make sense to (optionally) include the SQL version in the rows tab also?

Are you interested in adding the features above if I add seperate PRs?

**Comment by sosedoff** [comment]
I understand that you have a very specific use case for pgweb, but having an extra functionality just to show the sql queries being used in the browse view is an overkill imo. As i mentioned before, the best way to solve the problem is to implement query logging for all browse queries so that users can quickly glance at those in the history view.

Another solution would be having a smaller panel (aka "console") that will show all the queries that pgweb runs. This will however require extra development time, which i d'ont have at the moment. If you're interested - feel free to open a new PR. (P.S this is something that SequelPro does and its great).

Cheers.

**Comment by sosedoff** [comment]
Closing this for now. Part of the PR has been already merged, the rest is not going to make it in.

**Pull request closed without merging**
