### PR TITLE
beta: integration-testing

### PR DESCRIPTION
**Pull request by varp**

### CODE REVIEW

**Comment by varp** [comment]
And that? 🙂

**Comment by sosedoff** [comment]
Please update the PR if still interested. Otherwise im going to close it.

**Comment by varp** [comment]
OK!

**Comment by varp** [comment]
I’ll update the PR  on this week

**Comment by varp** [comment]
The PR is updated. Please check and give me feedback. The TravisCI pipeline fails because of TLS error during connecting to the GitHub. At the moment I don't why it fails, but I'm still thinking about it.

**Comment by varp** [comment]
Ok! I've resolved the issue with TLS using Alpine 3.8 as base image

**Comment by varp** [comment]
Are there any chances that the work will be merged in? Maybe I need to do some changes?

**Comment by varp** [comment]
I'm open to any constructive critic related to the code or something else, my friend =)

**Pull request closed without merging**
