### PR TITLE
opts.SortColumn must be escaped; fixes sorting on column with capitals

### PR DESCRIPTION
**Pull request by SjonHortensius**

### CODE REVIEW

**Comment by SjonHortensius** [comment]
Apparantly this PR duplicates #169

And yes; this breaks when a sorted column contains a capital letter

**Comment by sosedoff** [comment]
If you're familiar with Go, please include a simple unit test so that we can verify the feature works correctly. If you're not i'll add the test case myself. Let me know.

**Comment by SjonHortensius** [comment]
I'll look into it

**Comment by sosedoff** [comment]
Closing this in favor of #191

**Pull request closed without merging**
