### PR TITLE
Added binary codec `base58` as well as improving the help for `--binary-codec` flag

### PR DESCRIPTION
**Pull request by maoueh**

### CODE REVIEW

**Comment by sosedoff** [comment]
I think i remember why i didn't make the base64 a default (like i thought): there's no way to differentiate between raw binary data encoded as base64 and regular table content that is stored in the encoded format by the database owner. It's not a big deal, but could be a bit misleading.

On the other hand, i'd still prefer convention over configuration, so i'll give this a go and merge and everything's looking good. Thanks for the contribution!

**Comment by sosedoff** [comment]
Needs a test in here https://github.com/sosedoff/pgweb/blob/master/pkg/client/codec_test.go

**Comment by maoueh** [comment]
> I think i remember why i didn't make the base64 a default (like i thought): there's no way to differentiate between raw binary data encoded as base64 and regular table content that is stored in the encoded format by the database owner. It's not a big deal, but could be a bit misleading.

I'm not sure I understand the problem to be honest. Also when you said `i didn't make the base64 a default`, does this mean it's not enabled and you would like that I remove the `default` in the CLI description?

**Comment by maoueh** [comment]
> Needs a test in here https://github.com/sosedoff/pgweb/blob/master/pkg/client/codec_test.go

I'll add that.

**Comment by sosedoff** [comment]
Yea, i meant that binary encoding is currently disabled, tho i don't have a problem with switching the default to `base64` moving forward.

**Comment by sosedoff** [comment]
Looks like the correct base58 `hello world` is `StV1DL6CwTryKyV` :)

**Comment by sosedoff** [comment]
@maoueh can you fix the value? should be good then, you can ignore the appveyor failures

**Comment by maoueh** [comment]
Not sure how I could fucked up so big lol sorry.

**Pull request merged**
