### PR TITLE
Abocd

### PR DESCRIPTION
**Pull request by abocd**
I'm sorry. A version I modify is not very clear, this time I again only to the bindata.go do the modification mainly fixed static content for dynamic load, otherwise static directory file is useless.
很抱歉，上一个版本我修改的不是很清楚，这次我重新只对bindata.go做了修改，主要是修改固定静态内容为动态载入的方式，否则 static  目录下面的文件就没用了。

### CODE REVIEW

**Comment by sosedoff** [comment]
Were there any changes to the asset files? It looks like nothing was changed (except for bindata).

**Comment by abocd** [comment]
There is no modification of files asset, but I have changed the way of displaying files asset in bindata.
**Before change:**
```go
var _staticJsThemeTomorrowJs = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x94\x56\x7b\x6f\xe2\x46\x10\xff\x2a\x2e\xfd\x07\x24\x9b\x47\x02\x04\x13\xf1\x07\x21\x4e\xd5\xab\xd4\x36\x77\xcd\x55\xd7\xaa\xaa\x16\xef\xb0\xac\xb0\x77\xdd\x7d\x04\x10\xca\x77\xef\xac\x7d\x84\xc7\x2d\x8f\xf3\x0a\x33\xb6\x67\x7e\xf3\x9b\x87\xc7\x4b\x52\x68\x52\x98\x71\x01\xf5\x1a\xca\x2d\x33\x87\x1c\xcf\x32\x97\x4a\xc9\x65\x2d\xfc\xbb\xa6\xe0\x3f\xcb\x15\xd4\xc2\x1a\xac\x0a\xa9\x8c\x46\x29\x97\xd4\x66\xee\x96\x33\xc9\xf8\xb4\x45\x65\x5e\xfb\x27\x9c\x59\x91\x1a\x2e\x45\x1d\x42\x13\x8a\xc6\xc6\x34\xb9\x7e\x24\x6a\x31\xfa\xa1\x13\x9a\x66\xaa\xf5\x24\x23\x5a\x8f\x9c\x55\xb4\x73\x51\x3e\xf9\x03\x56\x66\x54\x6b\xee\x3f\x09\xdc\xd5\xbf\xcc\x1a\x03\x2a\xd8\x4c\x49\xba\x60\x4a\x5a\x41\x87\xc1\x8f\xb3\xbe\x5b\xf7\xa9\xcc\xa4\xc2\xcb\xee\x23\xae\xc9\x9b\xc7\xba\x50\x5c\x98\x28\x27\x8a\x71\x11\x6c\x96\x9c\x9a\xf9\x30\xe8\x14\xab\x7b\x0f\xdc\x91\xfd\x9e\xc7\x68\xeb\xe8\xa9\x3c\xae\xf0\x9b\x5a\xa5\x25\xb2\xde\x6a\x8e\x93\xf1\xd3\xf8\xd1\xa7\x89\xdc\x16\xa0\xa2\x8c\xac\x31\xca\xf2\x8e\x86\x0c\xca\x34\x1e\x05\xfd\xd8\x77\xeb\x10\xa3\x82\xb0\x99\xe1\x95\xd5\x11\x42\x75\x65\x88\x32\x88\x25\x57\x91\x9e\x13\x2a\x97\xc3\xa0\x8d\xeb\xb6\x58\x05\x6d\xfc\x6d\x83\xba\x92\x9c\x81\xe2\x90\x97\x62\xd3\xfa\x4d\xaf\x17\x06\xe5\xa9\xdd\xb8\x0e\x67\xaa\x10\x02\x90\x56\x55\x9b\x61\x10\x75\x1c\x1f\x5c\x51\x59\x1e\xa9\x28\xa8\xb2\x54\x81\x96\x19\xa7\x18\x7e\xc7\xad\xeb\xd0\x09\x46\xff\x0a\x51\x86\x6d\x7d\x94\xc4\xe4\xc9\x2d\x1f\x4a\xd5\x68\xd1\x09\xd3\xaa\x05\x02\x44\xa0\xa9\x5b\xdf\x53\x4a\xa0\xd1\x12\xe3\x71\x25\xf8\x36\x2a\x4f\x51\x2b\x5b\x2e\x5e\xb9\xe6\xd3\x0c\x76\x5d\x74\x3a\x05\x0b\x58\x3b\x17\xa1\x8f\x15\x18\xe2\xbb\xaf\x8d\x54\x84\xc1\x99\x47\xa5\x6c\xd6\x85\x5f\xc7\x16\x6e\x1a\xbc\xeb\xec\x58\x0e\xe2\x5e\x3c\x1e\x9c\x61\x59\xca\xb2\x00\x45\xcc\xfe\x3b\x72\x9b\xc4\x71\xec\x2d\x4d\x2a\x05\x36\xb1\xa8\x9c\xa5\x73\x82\xbd\x83\xa5\xf2\xb1\x3a\xd0\xcc\x88\x60\xf6\x44\x88\x07\x8a\xc2\xe6\xa0\x78\xea\xd3\x3b\xa0\x8c\xc3\x51\x95\x92\x15\xdc\x5c\x4a\xca\xd6\x83\x4f\xef\x95\x28\x4e\xb0\xb4\xd5\x8c\xc2\x78\xb0\x48\xb0\x97\x8a\xa7\xde\xe0\xae\x73\x39\x15\x25\xa1\x9d\x55\xbf\xdf\x8f\xfb\xf1\x89\x5e\x22\xae\xdd\x36\x47\x83\xcc\x33\xe2\x26\x83\x9b\xc1\xcd\x39\x90\x52\xa6\x50\x28\x48\x09\xb6\xf6\x35\x98\xa7\x3b\x62\x26\x33\xea\x9d\xb4\xdd\x9b\xbb\xce\x38\xf9\x3a\x07\xa2\xcb\x03\x17\x84\xe1\x66\x5d\x55\x13\xb3\x59\x81\x7f\xfd\x1c\x5d\xaa\xd4\x39\xbd\x6d\xa5\x76\x61\x56\xcc\x7c\x1c\x0e\xaa\xef\xbe\x74\xdf\xf7\xde\x4c\xe2\x38\x69\xb7\x7d\xc0\x73\x20\x94\x0b\xe6\x7d\xbb\x71\xe6\xd8\xe2\x92\x96\x36\xf8\x1d\x64\x3b\x57\x77\x9d\xc1\xc4\xef\xca\x97\x47\x43\xbc\xa0\x7b\xaa\xbb\x37\x83\x18\x74\x35\xb5\x06\x22\x67\x7e\x6a\x1e\x9d\x83\xad\xb8\x96\xa2\x02\x86\x7b\x8e\xeb\xca\x72\xba\x6f\x53\x99\xe7\xc8\x75\x6f\x40\x25\x71\x7b\xe0\xed\x22\x2e\x28\x6a\x46\xcc\x72\x7a\xf4\xe1\xb0\x2a\xab\x53\x62\xc8\x90\xe7\x38\x51\x5a\x85\x60\xd8\xe8\x1a\xfa\xdd\x90\x7f\x7e\xf8\xed\xe3\xb2\xfd\xcb\x4f\x4c\x8e\xf1\xf8\xf5\xd3\xcb\x3c\x79\x61\x4e\x4c\xdc\x69\x32\x19\x7f\x71\x7f\x7f\xb1\xe9\x17\x51\xde\x6d\x67\xc9\xf3\xe7\xe7\x9f\xf3\x3f\x7f\xef\xb6\xf0\x98\x75\xa7\xd4\xde\xce\x5a\x0f\xcb\x71\x36\x63\xa9\xa1\xf6\x61\xd0\x7b\x76\x9a\x0f\x1f\x3e\xbe\xf4\x12\xb5\xf8\xc0\x18\x1b\x8d\x1a\x81\xe2\x6c\x6e\x02\x05\x05\x10\x13\xad\xdf\x6a\xf7\x98\x85\x40\x8d\x70\xe7\xd6\x6c\xbe\xef\xc2\x1a\xf7\xaa\xc9\x73\xd7\x62\x13\xad\x3f\x95\xb9\xac\xbf\xef\xb0\xf6\x76\x61\x8d\xb7\xc6\xff\x01\x00\x00\xff\xff\x3a\x10\x34\xb4\xfc\x09\x00\x00")

func staticJsThemeTomorrowJsBytes() ([]byte, error) {
	return bindataRead(
		_staticJsThemeTomorrowJs,
		"static/js/theme-tomorrow.js",
	)
}
```

**After the change:**
```go
var _staticJsThemeTomorrowJs = []byte("")

func staticJsThemeTomorrowJsBytes() ([]byte, error) {
	return LoadFileContent("static/js/theme-tomorrow.js")
	//return bindataRead(
	//	_staticJsThemeTomorrowJs,
	//	"static/js/theme-tomorrow.js",
	//)
}
```

**Comment by sosedoff** [comment]
Does that mean you manually changed the bindata.go file?

**Comment by abocd** [comment]
I'm sorry, I was wrong, I do not know this document is generated

**Pull request closed without merging**
