### PR TITLE
Use bookmarks' name to connect

### PR DESCRIPTION
**Pull request by erdnaxeli**
This avoid to send the connection data back and forth. This also allow to not expose sensitive data like passwords.

The idea is to have a configuration on server-side which is unknown from the user on client-side.

### CODE REVIEW

**Comment by sosedoff** [comment]
Looks like i missed this PR, sorry about that. I'd like to get this merged, though. Would you be able to rebase your work with master? If not i can get the work done on my own copy of your branch.

**Comment by erdnaxeli** [comment]
Hi, 

I will do that this afternoon.

**Comment by erdnaxeli** [comment]
The pull request is up to date with master.

**Comment by sosedoff** [comment]
Does not seem that your branch includes all recent changes. Also, SSH is no longer works when connecting via bookmark name only.

**Pull request closed without merging**
