### PR TITLE
Discover database resources with third-party providers

### PR DESCRIPTION
**Pull request by sosedoff**
Initial pass at Discovery feature. 

- Heroku
- AWS (partially, no way to get db/user/pass for RDS instance)

This is highly experimental feature and still work-in-process.

### CODE REVIEW

**Comment by sosedoff** [comment]
@bsx thanks for  the feedback. i'll add the missing aurora stuff (i've used your code as a base) and aws config file support.

**Comment by sosedoff** [comment]
@bsx have a look at the latest build here, i've added AWS config support (with profiles). It does work, although it's kinda limited because there's no way to switch AWS profiles using the web UI.

**Comment by sosedoff** [comment]
@bsx ping

**Comment by bsx** [comment]
Hey, sorry for the delay. For the AWS config files i'd really recommend against parsing them yourself. I'd say if the access_key and secret_key aren't passed via CLI flags just hand of the credential acquisition to the SDK. It's way more flexible in its capabilities and can deal with all sorts of weird auth configs.

**Pull request closed without merging**
