### PR TITLE
Schema support using regclass

### PR DESCRIPTION
**Pull request by cbandy**
See #14.

- Button to refresh table list on demand
- List tables and views based on the current search path
- Use regclass to generate properly quoted table identifiers based on the search path

Issues:
- Button placement and styling. I just plopped some bootstrap around a [↻](http://www.fileformat.info/info/unicode/char/21bb/index.htm).
- Table names. Regclass does [the "right thing"](http://www.postgresql.org/docs/current/static/datatype-oid.html), prepending the schema only when absolutely necessary (i.e. only for tables with overlapping names AND only for schemata later in the search path.) For a user with multiple schemata and little overlap, this may be confusing to see... Though it matches the logic of unqualified lookups... User feedback may be necessary/best to handle this well.
- Order of table names. Given the above, I didn't [yet] pick anything by which to order the list of tables. When using search path, the most reasonable to me would be schama-search-path-order followed by alphabetical table name. Thoughts?

### CODE REVIEW

**Comment by AkeemMcLennon** [comment]
:+1: 
Im really interested in seeing this feature :-)

**Comment by alfonsodev** [comment]
:+1

**Comment by avitex** [comment]
Any news on this being pulled in? :smile:

**Comment by sosedoff** [comment]
Yes, eventually its going to make into master, but its a slow progress so i cant guarantee any ETA's at this time.

**Comment by avitex** [comment]
@sosedoff Cheers :+1:

**Comment by ManuelWeiss** [comment]
Can you please merge this PR? Seems like a lot of people are waiting for this feature.

**Comment by jerome-peng** [comment]
yes,also waiting this feature

**Comment by sosedoff** [comment]
Closing this obsolete PR, multiple schemas are implemented in master and will be part of the upcoming release.

**Pull request closed without merging**
