### PR TITLE
Import data from CSV file

### PR DESCRIPTION
**Pull request by koneko096**
Refers to #281

### CODE REVIEW

**Comment by sosedoff** [comment]
There are a couple of issues that i noticed:

- No way to specify delimiter for the imported CSV file
- When import fails, there's no error message
- The table name import field is too wide, it should probably take 1/4 or 1/3 of the page
- Panics

Example panic:

```
runtime error: invalid memory address or nil pointer dereference
/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 (0x102a81f)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:63 (0x10296ce)
	panicmem: panic(memoryError)
/usr/local/Cellar/go/1.8.3/libexec/src/runtime/signal_unix.go:290 (0x103fb0f)
	sigpanic: panicmem()
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/pkg/api/api.go:503 (0x14529b4)
	DataImport: defer file.Close()
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/context.go:98 (0x137ddfa)
	(*Context).Next: c.handlers[c.index](c)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/pkg/api/middleware.go:31 (0x1456089)
	dbCheckMiddleware.func1: c.Next()
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/context.go:98 (0x137ddfa)
	(*Context).Next: c.handlers[c.index](c)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/recovery.go:45 (0x138d86a)
	RecoveryWithWriter.func1: c.Next()
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/context.go:98 (0x137ddfa)
	(*Context).Next: c.handlers[c.index](c)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/logger.go:77 (0x138cb3f)
	LoggerWithWriter.func1: c.Next()
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/context.go:98 (0x137ddfa)
	(*Context).Next: c.handlers[c.index](c)
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/gin.go:290 (0x13843f0)
	(*Engine).handleHTTPRequest: context.Next()
/Users/sosedoff/go/src/github.com/sosedoff/pgweb/vendor/github.com/gin-gonic/gin/gin.go:271 (0x1383d0b)
```

**Comment by varp** [comment]
@icalF I can suggest you to use Posgres [COPY](https://www.postgresql.org/docs/9.6/static/sql-copy.html) function, which is faster than INSERT INTO

**Comment by sosedoff** [comment]
Closing due to no activity.

**Comment by budden** [comment]
Hi! I picked up this PR and want to finish it. Can you please elaborate about panics: how did you achieve it?

**Comment by budden** [comment]
I created one case of panic by specifying an incorrect structure, but it seem to have recovered from it successfully.

**Pull request closed without merging**
