### PR TITLE
Add sequence.

### PR DESCRIPTION
**Pull request by niiyz**
Add Sequences.

### CODE REVIEW

**Comment by sosedoff** [comment]
Could you please rebase and also make sure to run `make assets` ?

**Comment by niiyz** [comment]
I executed rebase and make assets. please confirm.

**Comment by sosedoff** [comment]
Pardon me, i meant squash not rebase. Just wanted to make sure there's a single commit with all your changes.

**Comment by niiyz** [comment]
I was aware . It is all of my change to the minute that are currently committed .

**Pull request merged**
