### PR TITLE
feat: add option to disable query timeout on long-running queries

### PR DESCRIPTION
**Pull request by varp**

### CODE REVIEW

**Comment by varp** [comment]
@sosedoff what about that?

**Comment by sosedoff** [comment]
I just checked the changes, not sure i want to have this checkbox on the bar. Maybe a better UX is to add a small "wrench" icon somewhere on the same bar (where we have "run", "explain", etc). When user clicks on it we can open up a small modal with timeout settings or anything that really belong there. Just my two cents.

**Comment by sosedoff** [comment]
Honestly, i'd prefer a `--query-timeout` param in the CLI at this point. Feel free to reopen.

**Comment by lucawen** [comment]
@sosedoff if you prefer a cli param, then do it! You already said that you do not have the time to do this and would like to have an open PR for this feature, so why did you close this PR just because you did not like it? The tool needs to be like the community needs it, not how you would like it to be

**Pull request closed without merging**
