### PR TITLE
Update client.go

### PR DESCRIPTION
**Pull request by xujif**
quote field in order condition

### CODE REVIEW

**Comment by sosedoff** [comment]
@xujif was not having quotes causing any issues?

**Comment by xujif** [comment]
@sosedoff  can not order the data when click the field which with uppercases

**Comment by sosedoff** [comment]
@xujif Could you provide an example SQL so i can reproduce, add a test and fix the issue?

**Comment by sosedoff** [comment]
Nevermind, i was able to fix the issue in #191.

**Pull request closed without merging**
