### PR TITLE
Add support for building snaps

### PR DESCRIPTION
**Pull request by igorljubuncic**
Hi Dan, following up on what we discussed, the exact details on how to publish the snap.

1. Install snapcraft & build snap

snap install snapcraft --classic --beta
git clone https://github.com/igorljubuncic/pgweb.git
cd pgweb
git checkout add-snapcraft
snapcraft

This command will generate a <pgweb-version>.snap file, something like pgweb_1.0_amd64.snap.

2. Test locally

This snap can be installed and tested locally with:

snap install pgweb_1.0_amd64.snap --dangerous

The --dangerous flag is necessary because the app (snap) hasn’t gone through the snap store review process and is not signed.

Once installed, the pgweb command can be executed, e.g.: snap run pgweb

3. Register dev account and pgweb name in the store

https://snapcraft.io/account.

snapcraft login
snapcraft register

4. Upload snap to the store. We use channels for diff levels of risk/stability. Edge is as the name implies, usually built from master, stable for the most stable release, you can also use beta and candidate.

snapcraft push pgweb_1.0_amd64.snap --release edge

5. Install from store

snap install pgweb --edge

That's it. Let me know if you have any questions.

### CODE REVIEW

**Comment by sosedoff** [comment]
Thanks for the PR, i'll give it a try some time this week.

**Comment by igorljubuncic** [comment]
Hey Dan,

Happy new year!

Did you get a chance to test the snaps? Do you have any questions or need any clarifications?

**Comment by sosedoff** [comment]
I did try to run the installation steps on OSX but had issues getting the snapcraft running (something to do with homebrew). Are those steps for linux only or they're exactly the same for OSX? 
I'll have some time this week to test again.

**Comment by igorljubuncic** [comment]
It should be straightforward:

brew install snapcraft
snapcraft (in the directory containing snapcraft.yaml)

**Comment by igorljubuncic** [comment]
Hey. Just a quick follow up. Anything I can do to help here and get you up and running with snaps?

**Comment by sosedoff** [comment]
Im afraid that snap support isnt going to be part of this repo. Maybe a better place for things like snap (or even homebrew) is `pgweb-distribution` repo or something like that. Current scope is to only release binaries and docker images. There is another PR that introduces K8S Helm that falls under same umbrella of installation instructions, so maybe it's a good time to revisit.

**Pull request closed without merging**
