### PR TITLE
Wip/query server timeout

### PR DESCRIPTION
**Pull request by goldfix**
hi Dan!

I made a small modify, to manage server timeout of query.
It's possible set a new parameter from command line (timeout) and all queries are blocked when exceed this execution time.

what do you think?

thanks

ciao
p

### CODE REVIEW

**Comment by sosedoff** [comment]
Couple of things here:

- There needs to be a an automated test for this feature to make sure it works on all supported postgres versions (9.x)
- Whats the reason for js timeout change to 1 hour?
- Probably a good idea to change new flag to `--query-timeout` (and the var in struct) so that its clear that timeout is related to sql stuff

**Comment by goldfix** [comment]
I agree,

1) I'm checking and modifying automated test.
2) well... I try to set js-timeout like server timeout, but I have a problem to parametrize app.js... I'm investigating (this is my first go-coding...).
3) ok

thanks

p

**Comment by goldfix** [comment]
Hi Dan,

I made recommended.

Thanks

ciao
p

**Comment by sosedoff** [comment]
Having an extra API endpoint just to fetch timeout setting is a bit overkill in my opinion. There arent any other options that could be exposed so i would really prefer to have a hardcoded "max" value for the timeout. 5 minutes sounds about right as pgweb was not designed to be running any queries that could take more time than that.

Also, since i dont have any windows machines around to test pgweb stuff, im not sure i understand why `FORCE_WIN_TEST` is "enabled" (by setting it to "0") by default.

**Comment by goldfix** [comment]
FORCE_WIN_TEST: I do not understood because you bypass test of client_test.go on windows  environment. Well for security I do not change your check and I prefer add this  environment variable to bypass your check.

And yes, I work on windows :)

thanks  
ciao
p

**Pull request closed without merging**
