### PR TITLE
Add AWS RDS instance discovery

### PR DESCRIPTION
**Pull request by bsx**
This PR adds the possibility to automatically discover AWS RDS instances and offer them in a dropdown to prefill the host and port fields.
* discovery is disabled by default
* region and credentials can be automatically discovered from EC2 metadata or the usualy AWS SDK config methods (~/.aws/config, env variables, ...)
* in read-only mode the endpoint for RDS clusters returned is the reader endpoint

### CODE REVIEW

**Comment by Garbee** [comment]
Is there an issue with some background on why this feature should be added, scoping it, and discussing config plans? It seems like a fairly massive PR to dump on a project out of the blue.

**Comment by sosedoff** [comment]
Interesting, i had a very similar use case for Heroku where i had to connect to a few databases. I made  a hacky "addon" for pgweb, but all this work is not open sourced.

**Comment by sosedoff** [comment]
@bsx how are you running pgweb? on your dev machine or on the EC2 instance ?

**Comment by bsx** [comment]
I'm running it on EC2 instances in multi session mode for multiple users.

**Comment by sosedoff** [comment]
@bsx Checking in, did you try the approach i described above?

**Comment by bsx** [comment]
Sorry, haven't had the time yet but I'll definitely check it out

**Comment by sosedoff** [comment]
@bsx Another ping, have you tried anything that i outlined in the previous posts?

**Comment by bsx** [comment]
I've played around with the "Connect" featuee a bit. Seems promising so far. I've noticed however that it is not possible to combine it with the "Lock Session" feature, but maybe I'm misunderstanding the session lock thing.
I'm currently thinking about a "companion" app that handles auth and connection details so the user would probably never see the connection form of pgweb itself.

**Comment by sosedoff** [comment]
@bsx @Garbee take a look at #391 PR.

Pushed out an initial feature set with 2 providers: Heroku and AWS. Technically speaking, existing bookmarks feature could be implemented as a provider since all providers are using Bookmark model to return connection details.

I find it really easy to connect to Heroku now since i don't even have to configure the API token with CLI flag, pgweb will load the token from `~/.netrc` file where Heroku CLI keeps its config. 

Here's how to enable the feature:

```
pgweb \
  --sessions \               # Turn on multi-session mode
  --discovery \              # Turn on discovery feature
  --heroku \                 # Enable Heroku provider
  --heroku-token=... \       # Heroku API token (optional) -> HEROKU_TOKEN
  --aws \                    # Enable AWS provider
  --aws-access-key=... \     # -> AWS_ACCESS_KEY
  --aws-secret-key=... \     # -> AWS_SECRET_KEY
  --aws-region=us-east-1     # -> AWS_REGION
```

You'd need to checkout git branch `discovery` to test out the feature. Just clone the repo, switch branch and run `make build`.

Let me know what do you think.

**Comment by sosedoff** [comment]
Ping! Would love to hear some feedback here.

**Comment by sosedoff** [comment]
Closing in favor of #391

**Pull request closed without merging**
